[package]
name = "xcp_idl_generator"
version = "1.0.0"
edition = "2024"

[dependencies]
ctor = "0.2.9"
#ctor = "0.4"
lazy_static = "1.5"
regex = "1.12.2"
xcp_idl_generator_derive = { path = "./xcp_idl_generator_derive/" }

[lib]
path = "src/lib.rs"
