[package]
name = "xcp_type_description"
version = "0.9.2"
edition = "2024"

[dependencies]
lazy_static = "1.4"
xcp_type_description_derive = { path = "./xcp_type_description_derive/" }

[lib]
path = "src/lib.rs"